# Generated by Django 5.0.7 on 2024-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/profile2.png",
                upload_to="profile_images/",
            ),
        ),
    ]
